#!/bin/bash

URL=http://debiandog.github.io/Misc/Xenial/amd64/Packages/SFS/vlc.squashfs
FILENAME="${URL##*/}"
./loadmodule -d /root/httpfs_mnt_$FILENAME/$FILENAME
umount -l /root/httpfs_mnt_$FILENAME
sleep 1
rmdir /root/httpfs_mnt_$FILENAME

